#DB CONFIGURATION
spring.datasource.url = jdbc:mysql://localhost:3306/vibehub_stg?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = root

jwt.secret = 4c9e2b7a1d6f3c8e5a0b2d9f7c4e1a6d8b3f0c5a9e2d7b1f6c8a4e3d9b2c7f5