

#DB CONFIGURATION
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/vibehub?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

#To create a table, we need to give DDL permission to Hibernate
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

jwt.secret = b7e2d9c4a1f693b8d5c0a7f9e2b4c6d1a8f3e7c5b9d0a2e6f1c4d8b7a9e3c2v5