#DB CONFIGURATION
spring.datasource.url = jdbc:mysql://localhost:3306/vibehub_stg?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = root

jwt.secret = 1m9e2bj6gd6f3c8e5K0okxaefd9f7c4e9a6d8b3f0c5a9e2d7b1f6c8a4e3d9b2c90a